#!/usr/bin/env bash

declare -i choice=3
if (( $choice==0 )); then

  for i in 1 2 3; do echo $i; done; echo
  for i in 1 2 3; do
    echo $i
  done

elif (($choice==1)); then

  for ((i=1; i<=10; i++)); do
    echo $i
  done

elif (($choice==3)); then

  declare -a fruits=("apple" "banana" "cherry")
  for i in ${fruits[@]}; do
    echo $i
  done

elif (($choice==4)); then

  declare -A arr
  arr["name"]="Scott"
  arr["id"]="1234"
  for i in "${!arr[@]}"; do
    echo $i: "${arr[$i]}"
  done

elif (($choice==5)); then

  for i in $(ls); do
    echo "Found a file: $i"
  done

fi
